package com.example.miniui.dao;

import com.example.miniui.entity.DepUser;
import java.util.List;

public interface DepUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_user
     *
     * @mbg.generated
     */
    int insert(DepUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_user
     *
     * @mbg.generated
     */
    DepUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_user
     *
     * @mbg.generated
     */
    List<DepUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DepUser record);
}