package com.example.miniui.dao;

import com.example.miniui.entity.User;
import com.example.miniui.entity.nTitle;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.github.pagehelper.Page;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Repository;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@CacheConfig(cacheNames = "users")
@Mapper
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Cacheable
    List<User> selectAll(@Param("searchName") String searchName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    int checkname(User user);

    @Cacheable
    int checkid(int i);

    @Cacheable
    List<Map> selectNTitle(int id);

    @Cacheable
    int findExistIdexcptit(int id);

    Page<HashMap> selectAllByPage(String searchname);

    void insertTitle(nTitle n);

    User selectByName(String name);


    List<User> selectAll1();

    void deleteAll();

    void insertAll(User record);
}