package com.example.miniui.entity;

import java.io.Serializable;

public class DepUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dep_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dep_user.rename
     *
     * @mbg.generated
     */
    private String rename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dep_user.dpm
     *
     * @mbg.generated
     */
    private String dpm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dep_user.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dep_user.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dep_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dep_user.id
     *
     * @return the value of dep_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dep_user.id
     *
     * @param id the value for dep_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dep_user.rename
     *
     * @return the value of dep_user.rename
     *
     * @mbg.generated
     */
    public String getRename() {
        return rename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dep_user.rename
     *
     * @param rename the value for dep_user.rename
     *
     * @mbg.generated
     */
    public void setRename(String rename) {
        this.rename = rename == null ? null : rename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dep_user.dpm
     *
     * @return the value of dep_user.dpm
     *
     * @mbg.generated
     */
    public String getDpm() {
        return dpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dep_user.dpm
     *
     * @param dpm the value for dep_user.dpm
     *
     * @mbg.generated
     */
    public void setDpm(String dpm) {
        this.dpm = dpm == null ? null : dpm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dep_user.pwd
     *
     * @return the value of dep_user.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dep_user.pwd
     *
     * @param pwd the value for dep_user.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dep_user.pid
     *
     * @return the value of dep_user.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dep_user.pid
     *
     * @param pid the value for dep_user.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rename=").append(rename);
        sb.append(", dpm=").append(dpm);
        sb.append(", pwd=").append(pwd);
        sb.append(", pid=").append(pid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}